### Crear albarán
POST http://localhost:3096/api/albaran
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODE3Mjc1ZjQ4YTNhMGZhOTZmZmNlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjM0Nzg3MSwiZXhwIjoxNzQ2MzU1MDcxfQ.kVKKeWgNIGfpRiMkN-G81TnMyjphkjKrKXxyu8lfgu8
Content-Type: application/json

{
  "clientId": "681727b248a3a0fa96ffcec6",
  "projectId": "6817281148a3a0fa96ffcecc",
  "format": "hours",
  "description": "Desarrollo backend para API",
  "workdate": "2025-04-29",
  "hours": 8
}
