POST http://localhost:3096/api/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZWI0YTNlZDJhNjYwYTliMTllZGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTkzOTI3NCwiZXhwIjoxNzQ1OTQ2NDc0fQ.jeK2mAiy_rA9uPcps6VmZX0MrNfuEGWx2Ujqz3ypZNU
Content-Type: application/json

{
  "name": "Proyecto Tienda Online12",
  "description": "Desarrollo de eCommerce",
  "client": "68109e7bfd15f4b700ea4e96"
}

### Actualizar proyecto por ID
PUT http://localhost:3096/api/project/680d04fd59c12b3a09c631bd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBlMTY4NTQ1OGRmNzM0MmM5NjAyZDYiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTc1MzczMywiZXhwIjoxNzQ1NzYwOTMzfQ.GRMwZIIISZg7842UPLxv-5Pf394XnZ1zfa7qkbwYqwo
Content-Type: application/json

{
  "name": "Proyecto Tienda Online Actualizado Bien",
  "description": "Tienda online completa con pasarela de pago"
}
### Obtener todos los proyectos
GET http://localhost:3096/api/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZWI0YTNlZDJhNjYwYTliMTllZGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTkzOTI3NCwiZXhwIjoxNzQ1OTQ2NDc0fQ.jeK2mAiy_rA9uPcps6VmZX0MrNfuEGWx2Ujqz3ypZNU
Content-Type: application/json



### Obtener proyecto por ID
GET http://localhost:3096/api/project/680d04fd59c12b3a09c631bd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBlMTY4NTQ1OGRmNzM0MmM5NjAyZDYiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTc1MzczMywiZXhwIjoxNzQ1NzYwOTMzfQ.GRMwZIIISZg7842UPLxv-5Pf394XnZ1zfa7qkbwYqwo
Content-Type: application/json


### Archivar proyecto
PATCH http://localhost:3096/api/project/680d04fd59c12b3a09c631bd/archivar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBlMTY4NTQ1OGRmNzM0MmM5NjAyZDYiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTc1MzczMywiZXhwIjoxNzQ1NzYwOTMzfQ.GRMwZIIISZg7842UPLxv-5Pf394XnZ1zfa7qkbwYqwo
Content-Type: application/json


### Eliminar proyecto (hard delete)
DELETE http://localhost:3096/api/project/680e16ff458df7342c9602e7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBlMTY4NTQ1OGRmNzM0MmM5NjAyZDYiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTc1MzczMywiZXhwIjoxNzQ1NzYwOTMzfQ.GRMwZIIISZg7842UPLxv-5Pf394XnZ1zfa7qkbwYqwo


### Listar proyectos archivados
GET http://localhost:3096/api/project/archivados
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBlMTY4NTQ1OGRmNzM0MmM5NjAyZDYiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTc1MzczMywiZXhwIjoxNzQ1NzYwOTMzfQ.GRMwZIIISZg7842UPLxv-5Pf394XnZ1zfa7qkbwYqwo


### Recuperar proyecto archivado
PATCH http://localhost:3096/api/project/680d04fd59c12b3a09c631bd/recuperar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODBlMTY4NTQ1OGRmNzM0MmM5NjAyZDYiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTc1MzczMywiZXhwIjoxNzQ1NzYwOTMzfQ.GRMwZIIISZg7842UPLxv-5Pf394XnZ1zfa7qkbwYqwo
